POST http://localhost:8080/voucher-categories
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjE3ODMxMTgsInVzZXJJZCI6Wzk3LDk4LDk5LDQ5LDUwLDUxXSwidXNlck5hbWUiOls3OSwxMDcsOTcsMzIsODAsMTE0LDEwNSwxMTAsOTcsMTE0LDEwNiw5NywxMjEsOTddLCJyb2xlIjpbNzksODAsNjksODIsNjUsODQsNzksODJdfQ.xvORBrqKe35JxT1EBlJ0glTSTrN_YFUQNEr86FSyl3Q

{
    "categoryName": "Voucher 3 - 5Mbps",
    "priceBasic": 10000,
    "durationValue": 3,
    "durationUnit": "HOUR",
    "createdBy": "SYSTEM"
}

###

POST http://localhost:8080/sites
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjIxNzM5MzksInVzZXJJZCI6Wzk3LDk4LDk5LDQ5LDUwLDUxXSwidXNlck5hbWUiOls3OSwxMDcsOTcsMzIsODAsMTE0LDEwNSwxMTAsOTcsMTE0LDEwNiw5NywxMjEsOTddLCJyb2xlIjpbNzksODAsNjksODIsNjUsODQsNzksODJdfQ.fuVlQ12yziP4qa_iWf1f5Oepyfx3UulJ-r17I435AVI

{
    "siteName": "MENGWITANI JAYA RAYA - AGOY",
    "address": "Jalan Raya Mengwitani, Mengwi, Badung",
    "createdBy": "SYSTEM"
}

###

POST http://localhost:8080/vouchers
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjIxOTMzMTMsInVzZXJJZCI6Wzk3LDk4LDk5LDQ5LDUwLDUxXSwidXNlck5hbWUiOls3OSwxMDcsOTcsMzIsODAsMTE0LDEwNSwxMTAsOTcsMTE0LDEwNiw5NywxMjEsOTddLCJyb2xlIjpbNzksODAsNjksODIsNjUsODQsNzksODJdfQ.OzkhALtzGpR657-Vg_E826eOHM6v7AJMlynDynG41Cs

{
    "voucherCategoryId": 3,
    "siteId": 1
}

###

POST http://localhost:8080/_create-jwt
Content-Type: application/json

###

GET http://localhost:8080/voucher-categories
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjE3ODcxODEsInVzZXJJZCI6Wzk3LDk4LDk5LDQ5LDUwLDUxXSwidXNlck5hbWUiOls3OSwxMDcsOTcsMzIsODAsMTE0LDEwNSwxMTAsOTcsMTE0LDEwNiw5NywxMjEsOTddLCJyb2xlIjpbNzksODAsNjksODIsNjUsODQsNzksODJdfQ.Tgl_PE6zLNhorxFJ9B1nCqCL5Bby6COB-gfXnKctVG4

###

POST  http://localhost:8080/internal/ids
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMTgyZjI3ZmMtZjNhNC00OTdjLWI3N2YtODE1NTJlNjM4NDRmIiwicnQiOmZhbHNlLCJleHAiOjE2NTkyNDIxNzUsImlhdCI6MTY1OTIzODU3NSwiaXNzIjoiV2FydGVrLUlEIiwibmFtZSI6IklHTiBPa2EgUHJpbmFyamF5YSIsInJvbGVzIjpbIm1pdHJhX21hbmFnZXIiXSwicHRfY29kZSI6IiJ9.q_4KceffflUMV2aMn4hTV9Dh-nQZvz5I2zMopA2Kh0fj0AAoGoTTrwafwA7a_KwO-usyB6XnN8Zv_xJEG80iYw
Svc-User: internalService
Svc-Pass: internalServiceUser!!

{
    "ids": [
        {
            "id": "2e0e3cae-fa9f-49ce-9991-1556ccd5e1c2"
        },
        {
            "id": "810e0fdb-54d2-4556-8a85-c82e05393c14"
        },
        {
            "id": "cfce77b4-2efa-4cc2-ac24-b5f4c5f13afa"
        },
        {
            "id": "a4729fc2-6a28-4ea7-8e77-217d5d77a180"
        },
        {
            "id": "be03d17a-ee3a-4066-ad1e-253ef8b9f28c"
        }
    ]
}

###

POST https://property-advertising-svc-api.tinggal.id/v1/properties/options/property-detail-types
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI0QWd5V2ZpVmt2RDRDRFNNZG90VU5reVloeSIsInVzZXJUeXBlIjoiUFJPVklERVIiLCJpZE9yZ2FuaXphdGlvbiI6IjI0QWh2REFVMW1NTmRIdkxPbkJLcHJ3RHNkQyIsImlhdCI6MTY0MzA3OTUyNiwiZXhwIjoxNjc0NjE1NTI2fQ.75tO4bH28m85EtNuVkFmRmSHKK7n2KayMGKw440Or2Y
