POST http://localhost:8080/api/_create-jwt
Content-Type: application/json
Accept: application/json

###

POST http://localhost:8080/api/sites
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjM1MDY0NjcsInVzZXJJZCI6Wzk3LDk4LDk5LDQ5LDUwLDUxXSwidXNlck5hbWUiOls3OSwxMDcsOTcsMzIsODAsMTE0LDEwNSwxMTAsOTcsMTE0LDEwNiw5NywxMjEsOTddLCJyb2xlIjpbNzksODAsNjksODIsNjUsODQsNzksODJdfQ.fN_nsWQxrHFjJWlM5u3KJIubgAVUKSIEzf68aUnZznQ

{
    "sellingPricePercentage": 3,
    "siteName": "Cell & Net",
    "address": "Jalan Raya, Anjatan, Kec. Anjatan, Kabupaten Indramayu, Jawa Barat 45256",
    "createdBy": "SYSTEM"
}

###

POST http://localhost:8080/api/voucher-categories
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjM1MDY0NjcsInVzZXJJZCI6Wzk3LDk4LDk5LDQ5LDUwLDUxXSwidXNlck5hbWUiOls3OSwxMDcsOTcsMzIsODAsMTE0LDEwNSwxMTAsOTcsMTE0LDEwNiw5NywxMjEsOTddLCJyb2xlIjpbNzksODAsNjksODIsNjUsODQsNzksODJdfQ.fN_nsWQxrHFjJWlM5u3KJIubgAVUKSIEzf68aUnZznQ

{
    "categoryName": "3 Jam",
    "priceBasic": 3000,
    "durationValue": 3,
    "durationUnit": "HOUR",
    "createdBy": "SYSTEM"
}

###

POST http://localhost:8080/api/vouchers
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjQ2NTAzODgsInVzZXJJZCI6Wzk3LDk4LDk5LDQ5LDUwLDUxXSwidXNlck5hbWUiOls3OSwxMDcsOTcsMzIsODAsMTE0LDEwNSwxMTAsOTcsMTE0LDEwNiw5NywxMjEsOTddLCJyb2xlIjpbNzksODAsNjksODIsNjUsODQsNzksODJdfQ.px3bWp9tbKdsQqtQoOCQ4kS16RxPEt45aNnwI4nYViE

{
    "voucherCategoryId": 1,
    "siteId": 1,
    "maxMultiDevice": null
}

###

POST http://localhost:8080/api/voucher-reactivations
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjQ2Mzc0ODAsInVzZXJJZCI6Wzk3LDk4LDk5LDQ5LDUwLDUxXSwidXNlck5hbWUiOls3OSwxMDcsOTcsMzIsODAsMTE0LDEwNSwxMTAsOTcsMTE0LDEwNiw5NywxMjEsOTddLCJyb2xlIjpbNzksODAsNjksODIsNjUsODQsNzksODJdfQ.cAC7gPYxIxgL2Ei4xaIfX-5fEuP1Uwmp2POy3-Ukvcg

{
    "voucherCode": "249221OJKWLAYK"
}

###

DELETE http://localhost:8080/api/voucher-usages
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjQ2NTAzODgsInVzZXJJZCI6Wzk3LDk4LDk5LDQ5LDUwLDUxXSwidXNlck5hbWUiOls3OSwxMDcsOTcsMzIsODAsMTE0LDEwNSwxMTAsOTcsMTE0LDEwNiw5NywxMjEsOTddLCJyb2xlIjpbNzksODAsNjksODIsNjUsODQsNzksODJdfQ.px3bWp9tbKdsQqtQoOCQ4kS16RxPEt45aNnwI4nYViE

{
    "voucherCode": "249221BKRQDP1R"
}

